# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
CONFIG += c++17
QT += core gui widgets
INCLUDEPATH += ./include/opensource/spdlog-1/include

TEMPLATE = app
TARGET = drawbloodrobot
DESTDIR = ./buildout/x64/Debug
CONFIG += debug console
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
HEADERS += ./ArmPlateDevice.h \
    ./Controller.h \
    ./RobotArmDevice.h \
    ./SyringeDevice.h \
    ./SystemDevice.h \
    ./UltrasoundDevice.h \
    ./SystemDeviceUI.h \
    ./ArmPlateDeviceUI.h \
    ./RobotArmDeviceUI.h \
    ./UltrasoundDeviceUI.h \
    ./SyringeDeviceUI.h \
    ./ArmPlateDeviceSim.h \
    ./ControllerUIAdapter.h \
    ./DeviceUI.h \
    ./RobotArmDeviceSim.h \
    ./SimuDevicesPanel.h \
    ./SyringeDeviceSim.h \
    ./UltrasoundDeviceSim.h \
    ./statemachine/DeviceErrorHandler.h \
    ./statemachine/DeviceErrorHandlerAbnormal.h \
    ./statemachine/DeviceErrorHandlerNormal.h \
    ./statemachine/DeviceOperaHandler.h \
    ./statemachine/DeviceOperaHandlerAbnormal.h \
    ./statemachine/DeviceOperaHandlerNormal.h \
    ./statemachine/DeviceStateHandler.h \
    ./statemachine/DeviceStateHandlerAbnormal.h \
    ./statemachine/DeviceStateHandlerNormal.h \
    ./statemachine/DeviceTemplateHandler.h \
    ./statemachine/IDeviceErrorHandler.h \
    ./statemachine/IDeviceOperaHandler.h \
    ./statemachine/IDeviceStateHandler.h
SOURCES += ./ArmPlateDevice.cpp \
    ./ArmPlateDeviceSim.cpp \
    ./ArmPlateDeviceUI.cpp \
    ./Controller.cpp \
    ./ControllerUIAdapter.cpp \
    ./DeviceUI.cpp \
    ./main.cpp \
    ./RobotArmDevice.cpp \
    ./RobotArmDeviceSim.cpp \
    ./RobotArmDeviceUI.cpp \
    ./SimuDevicesPanel.cpp \
    ./SyringeDevice.cpp \
    ./SyringeDeviceSim.cpp \
    ./SyringeDeviceUI.cpp \
    ./SystemDevice.cpp \
    ./SystemDeviceUI.cpp \
    ./UltrasoundDevice.cpp \
    ./UltrasoundDeviceSim.cpp \
    ./UltrasoundDeviceUI.cpp \
    ./statemachine/DeviceErrorHandler.cpp \
    ./statemachine/DeviceErrorHandlerAbnormal.cpp \
    ./statemachine/DeviceErrorHandlerNormal.cpp \
    ./statemachine/DeviceOperaHandler.cpp \
    ./statemachine/DeviceOperaHandlerAbnormal.cpp \
    ./statemachine/DeviceOperaHandlerNormal.cpp \
    ./statemachine/DeviceStateHandler.cpp \
    ./statemachine/DeviceStateHandlerAbnormal.cpp \
    ./statemachine/DeviceStateHandlerNormal.cpp
FORMS += ./ArmPlateDeviceUI.ui \
    ./RobotArmDeviceUI.ui \
    ./SimuDevicesPanel.ui \
    ./SyringeDeviceUI.ui \
    ./SystemDeviceUI.ui \
    ./UltrasoundDeviceUI.ui
